### ISSUE TITLE
Reservations Summary - Error (v14)

### ISSUE THREAD

**Issue by tphole** [OCA/vertical-hotel#184]
I get an error when trying to open the Reservations Summary section. The Error is as below
-Odoo Community v14
Traceback:
Error: QWeb2: Template 'RoomSummary' not found
    at Object.exception (https://odoo-110766-0.cloudclusters.net/web/content/831-f3eb701/web.assets_common.js:4385:7)
    at Engine._render (https://odoo-110766-0.cloudclusters.net/web/content/831-f3eb701/web.assets_common.js:4430:103)
    at Engine.render (https://odoo-110766-0.cloudclusters.net/web/content/831-f3eb701/web.assets_common.js:4426:151)
    at Class.renderElement (https://odoo-110766-0.cloudclusters.net/web/content/832-f272ce3/web.assets_backend.js:8485:650)
    at prototype.<computed> [as renderElement] (https://odoo-110766-0.cloudclusters.net/web/content/831-f3eb701/web.assets_common.js:4620:488)
    at https://odoo-110766-0.cloudclusters.net/web/content/831-f3eb701/web.assets_common.js:4948:6

**Comment by JayVora-SerpentCS** [comment]
@tphole Can you retry in latest version please?
