### ISSUE TITLE
hotel_reservation - ImportError: No module named wizard

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-hotel#4]
I tried to install hotel_reservation and I get the following error:

```
Server Traceback (most recent call last):
  File "/home/max/openerp/hotel/git/odoo/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/max/openerp/hotel/git/odoo/openerp/netsvc.py", line 300, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/max/openerp/hotel/git/odoo/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/home/max/openerp/hotel/git/odoo/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/max/openerp/hotel/git/odoo/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/max/openerp/hotel/git/odoo/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/max/openerp/hotel/git/odoo/addons/audittrail/audittrail.py", line 532, in execute_cr
    return fct_src(cr, uid, model, method, *args, **kw)
  File "/home/max/openerp/hotel/git/odoo/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/max/openerp/hotel/git/odoo/openerp/addons/base/module/module.py", line 426, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/max/openerp/hotel/git/odoo/openerp/addons/base/module/module.py", line 473, in _button_immediate_function
    _, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "/home/max/openerp/hotel/git/odoo/openerp/pooler.py", line 39, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/loading.py", line 159, in load_module_graph
    load_openerp_module(package.name)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/module.py", line 405, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/max/openerp/hotel/git/odoo/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/max/openerp/hotel/git/hotel/hotel_reservation/__init__.py", line 22, in <module>
    import wizard
  File "/home/max/openerp/hotel/git/hotel/hotel_reservation/wizard/__init__.py", line 21, in <module>
    import hotel_reservation_wizard
  File "/home/max/openerp/hotel/git/hotel/hotel_reservation/wizard/hotel_reservation_wizard.py", line 28, in <module>
    import wizard
ImportError: No module named wizard
```

**Comment by JayVora-SerpentCS** [comment]
Works in v10, hence closing.
