### ISSUE TITLE
Hotel management dashboard error

### ISSUE THREAD

**Issue by infomate** [OCA/vertical-hotel#43]
Hello,
Here's my test system:
Ubuntu 18 / odoo 10 / Hotel Management app
I am testing the Hotel management app.  If I open the dashboard and try to minimize/maximize (-/+) the dashboard contents an error window pops-up.
If I close the window the app still works.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
TypeError: edit_custom() takes exactly 3 arguments (2 given)

**Comment by JayVora-SerpentCS** [comment]
@infomate Can you please try with the latest version ?

**Comment by JayVora-SerpentCS** [comment]
We are sure this would work normal with latest code.
