### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined in view_hotel_room_kanban

### ISSUE THREAD

**Issue by hudson940** [OCA/vertical-hotel#59]
Odoo version 11.0 
when I open kanban view room I get this error. 

`http://localhost:8069/web?debug#view_type=list&model=hotel.room&action=353:41
Seguimiento:
TypeError: Cannot read property 'value' of undefined
    at Engine.eval (eval at _render (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:3731:73), <anonymous>:41:122)
    at Engine._render (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:3730:296)
    at Engine.render (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:3730:151)
    at Engine._render (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:3734:57)
    at Engine.render (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:3730:151)
    at Class._render (http://localhost:8069/web/content/334-2faeea2/web.assets_backend.js:1539:118)
    at http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/311-e5376f5/web.assets_common.js:802:649)`

**Comment by JayVora-SerpentCS** [comment]
@nikul-serpentcs Please check.
cc @vimalpatelserpentcs

**Comment by hudson940** [comment]
sorry, my version did not have `<field name="id" />` in view_hotel_room_kanban.

**Comment by vimalpatelserpentcs** [comment]
@hudson940 @JayVora-SerpentCS This issue raise due to missing `<field name="id" />` fields in
in view_hotel_room_kanban, So would you please take the latest pull and check again.

Thank you
