### ISSUE TITLE
object has no attribute 'get_base_url'

### ISSUE THREAD

**Issue by therealmjk** [OCA/vertical-hotel#76]
Hi all 
I get this error when i try to send reservation email odoo 12. Please help

`System Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_273_7008
AttributeError: 'hotel.reservation' object has no attribute 'get_base_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/mail/wizard/mail_compose_message.py", line 193, in action_send_mail
    self.send_mail()
  File "/opt/odoo/addons/website_sale/models/mail_compose_message.py", line 21, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/opt/odoo/addons/mail/wizard/mail_compose_message.py", line 267, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/opt/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 2061, in message_post
    self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
    return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 2083, in _message_post_after_hook
    mail_auto_delete=mail_auto_delete,
  File "/opt/odoo/addons/mail/models/mail_message.py", line 1060, in _notify
    model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/addons/mail/models/mail_message.py", line 1140, in _notify_recipients
    self.env['res.partner']._notify(self, partner_email_rdata, record, force_send=force_send, send_after_commit=send_after_commit, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/addons/mail/models/res_partner.py", line 135, in _notify
    mail_body = base_template.render(template_ctx, engine='ir.qweb', minimal_qcontext=True)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 318, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1293, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'hotel.reservation' object has no attribute 'get_base_url'
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_273_7008
AttributeError: 'hotel.reservation' object has no attribute 'get_base_url'

Error to render compiling AST
AttributeError: 'hotel.reservation' object has no attribute 'get_base_url'
Template: 273
Path: /templates/t/table/tr[1]/td/table/tbody/tr[1]/td/t[3]
Node: <t t-set="base_url" t-value="record.get_base_url()"/>`

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs please check.

**Comment by therealmjk** [comment]
solved by adding

`    @api.multi
    def get_base_url(self):
        return ''

    @api.multi
    def _get_share_url(self, redirect=False, signup_partner=False, pid=None):
        return True`

**Comment by dhruvitaSerpentCS** [comment]
@therealmjk , Fixed the issue in this PR #77  so please look into it.
